name: Build and deploy demo

on:
  repository_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repo
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Create auth.json
      run: |
        echo "{\"github_personal_token\": \"$GITHUB_ACCESS_TOKEN\"}" > auth.json
    - name: Fetch the repos
      run: |-
        github-to-sqlite repos github.db simonw dogsheep
        sqlite-utils tables --counts github.db
    - name: Fetch releases, commits, issues
      run: |-
        # Just run against repos labelled with 'datasette-io'
        sqlite-utils github.db "
        select full_name from repos where rowid in (
            select repos.rowid from repos, json_each(repos.topics) j
            where j.value = 'datasette-io'
        )" --csv --no-headers | while read repo;
            do github-to-sqlite releases \
                    github.db $(echo $repo | tr -d '\r');
                sleep 2;
            done;
            do github-to-sqlite commits \
                    github.db $(echo $repo | tr -d '\r');
                sleep 2;
            done;
            do github-to-sqlite issues \
                    github.db $(echo $repo | tr -d '\r');
                sleep 2;
            done;
        sqlite-utils tables --counts github.db
    - name: Set up Cloud Run
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun github.db \
            --service github-to-sqlite \
            --title "gitub-to-sqlite demo" \
            --about "github-to-sqlite" \
            --about_url "https://github.com/dogsheep/github-to-sqlite"
